name: "CD"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Draft the release notes
        uses: release-drafter/release-drafter@v6.0.0
        with:
          publish: false
          tag: v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
